Remove or define undefined variables
tripal/tripal_galaxy pull request #124
Opened 2018-10-22 12:50 UTC by almasaeed2010

This PR adds to #119 and simply removes references to undefined variables that were causing errors. 

Note there a re a couple of `transactions` that were not defined so I simply removed them. If instead you'd rather we define the transaction let me know.

Thanks!

2018-11-29 23:08 UTC, spficklin commented
Hi @almasaeed2010 thanks for the PR.  I think this code will wipe out some of the newer changes we've made. I'm not sure why it doesn't give a merge conflict.  But for example, one line of code prints the report, but in the older version there's an if statement for lob logging that gets removed.  Can you pull the most recent code and see if the fixes in this PR still apply?

2018-11-30 05:14 UTC, spficklin requested changes

2018-11-30 05:14 UTC, spficklin commented on api/tripal_galaxy.api.inc
> +function tripal_galaxy_invoke_workflow($galaxy, $workflow_id, $parameters,
Here's an example of a change that I think will break things.  We have changed the function `function tripal_galaxy_invoke_workflow` to look like this:

https://github.com/tripal/tripal_galaxy/blob/7a4bb4bc4fd4a7c45954d872e0babb8c7cbf324a/api/tripal_galaxy.api.inc#L324-L329

But in this PR it alters that. I think it's trying to reset it to what it was before:

2018-11-30 13:33 UTC, almasaeed2010 commented
Thanks for catching @spficklin! I'll submit a new PR since the changes are actually very simple.

2018-11-30 13:33 UTC, closed without merging